package io.cfarb.exec;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.cfarb.model.Side;
import io.cfarb.model.SymbolFilter;
import io.cfarb.util.FixedPoint;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeUnit;
import org.jboss.logging.Logger;

/**
 * Submits one order and unconditionally reconciles its terminal state against the venue — shared by
 * {@link CycleExecutor} (forward legs) and {@link Unwinder} (reverse legs) so there is exactly one
 * place that knows the real MEXC wire contract (cf-arb-bot-review-plan.md Tier 1 steps 1.5/1.6).
 *
 * <p><b>Why every leg queries, not only a timed-out one:</b> {@code POST /api/v3/order}'s response
 * does not carry {@code executedQty}/{@code cummulativeQuoteQty} at all (confirmed against MEXC's
 * published spot v3 API reference 2026-09-07) — only {@code symbol,orderId,orderListId,price,
 * origQty,type,side,transactTime}. The previous design read fill quantities out of that response
 * and would have silently treated every single live order as a zero-fill. Fill data comes from a
 * follow-up {@link MexcRestClient#queryOrder}; per-fill commission comes from a further
 * {@link MexcRestClient#listTrades}, best-effort (a failure there degrades to the symbol's published
 * taker rate, never blocks on an otherwise-confirmed fill).
 *
 * <p>{@code origClientOrderId} is generated by the caller before the placement request is sent, so
 * reconciliation works identically whether the placement call succeeded, was rejected, or timed out
 * — the order may have reached the venue despite a client-side failure, and this is the only way to
 * find out. If reconciliation itself cannot establish a terminal state, the leg is marked
 * {@link CycleState.LegStatus#UNKNOWN} and the caller must never guess past that (Terra Major 4 /
 * Grok Major 6: an ambiguous order must never be silently treated as either filled or unfilled).
 */
final class OrderReconciler {

    private static final Logger LOG = Logger.getLogger(OrderReconciler.class);
    private static final ObjectMapper MAPPER = new ObjectMapper();

    private final MexcOrderApi rest;
    private final String orderType;
    private final long legTimeoutMs;

    OrderReconciler(MexcOrderApi rest, String orderType, long legTimeoutMs) {
        this.rest = rest;
        this.orderType = orderType;
        this.legTimeoutMs = legTimeoutMs;
    }

    /** Submit {@code leg}'s already-populated {@code requestedBaseQtyFixed}/{@code requestedPriceFixed}
     * on {@code symbol}/{@code side}, then reconcile. Mutates {@code leg} in place; never throws --
     * every failure mode is captured as a {@link CycleState.LegStatus}. */
    void submitAndReconcile(String symbol, Side side, SymbolFilter filter, CycleState.Leg leg) {
        String params = CycleExecutor.buildOrderParams(symbol, side, leg.requestedBaseQtyFixed,
                leg.requestedPriceFixed, filter, leg.clientOrderId, orderType);

        String placedOrderId = null;
        try {
            String resp = rest.placeOrder(params, legTimeoutMs).get(legTimeoutMs, TimeUnit.MILLISECONDS);
            placedOrderId = readTextField(resp, "orderId");
        } catch (Exception e) {
            logAttemptFailure("place", symbol, leg.clientOrderId, e);
            // Fall through to reconciliation regardless -- see class javadoc.
        }

        String orderId = placedOrderId;
        try {
            String resp = rest.queryOrder(symbol, leg.clientOrderId, legTimeoutMs).get(legTimeoutMs, TimeUnit.MILLISECONDS);
            JsonNode node = MAPPER.readTree(resp);
            leg.executedBaseQtyFixed = FixedPoint.fromDouble(doubleField(node, "executedQty"));
            leg.executedQuoteFixed = FixedPoint.fromDouble(doubleField(node, "cummulativeQuoteQty"));
            if (orderId == null && node.hasNonNull("orderId")) {
                orderId = node.get("orderId").asText();
            }
        } catch (Exception e) {
            logAttemptFailure("reconcile", symbol, leg.clientOrderId, e);
            leg.status = CycleState.LegStatus.UNKNOWN;
            return; // venue truth is unknown -- never infer a fill/no-fill outcome from here
        }

        if (leg.executedBaseQtyFixed <= 0) {
            leg.status = CycleState.LegStatus.ZERO_FILL;
        } else if (leg.executedBaseQtyFixed < leg.requestedBaseQtyFixed) {
            leg.status = CycleState.LegStatus.PARTIAL;
        } else {
            leg.status = CycleState.LegStatus.FILLED;
        }

        if (leg.executedBaseQtyFixed > 0 && orderId != null) {
            fetchCommission(symbol, orderId, leg);
        }
        leg.commissionEstimated = leg.commissionAsset == null;
    }

    private void fetchCommission(String symbol, String orderId, CycleState.Leg leg) {
        try {
            String resp = rest.listTrades(symbol, orderId, legTimeoutMs).get(legTimeoutMs, TimeUnit.MILLISECONDS);
            JsonNode arr = MAPPER.readTree(resp);
            double sum = 0;
            String asset = null;
            for (JsonNode t : arr) {
                sum += doubleField(t, "commission");
                if (asset == null && t.hasNonNull("commissionAsset")) {
                    asset = t.get("commissionAsset").asText();
                }
            }
            if (asset != null) {
                leg.commissionAsset = asset;
                leg.commissionFixed = FixedPoint.fromDouble(sum);
            }
        } catch (Exception e) {
            LOG.warnf("[exec] commission lookup failed for %s orderId=%s: %s -- falling back to the "
                    + "published taker rate for this leg's PnL", symbol, orderId, e.toString());
        }
    }

    /** Net proceeds in the leg's TO-asset units, after fees -- the actual per-fill commission when
     * it was confirmed in the asset actually received, otherwise the symbol's published taker rate
     * as a fallback (cf-arb-bot-review-plan.md Tier 1 step 1.5: never treat an estimate as a
     * confirmed commission, but never block PnL accounting on an unavailable one either). */
    static long netProceeds(Side side, SymbolFilter filter, CycleState.Leg leg) {
        long raw = side == Side.ASK ? leg.executedBaseQtyFixed : leg.executedQuoteFixed;
        if (raw <= 0) {
            return 0;
        }
        String receivedAsset = side == Side.ASK ? filter.baseAsset() : filter.quoteAsset();
        if (!leg.commissionEstimated && leg.commissionAsset != null && leg.commissionAsset.equals(receivedAsset)) {
            return Math.max(0, raw - leg.commissionFixed);
        }
        return FixedPoint.mulDiv(raw, filter.takerFeeMultiplierFixed(), FixedPoint.SCALE);
    }

    private static double doubleField(JsonNode node, String field) {
        JsonNode v = node.get(field);
        return v == null ? 0.0 : v.asDouble(0.0);
    }

    private static String readTextField(String json, String field) {
        try {
            JsonNode node = MAPPER.readTree(json);
            return node.hasNonNull(field) ? node.get(field).asText() : null;
        } catch (Exception e) {
            return null;
        }
    }

    private void logAttemptFailure(String stage, String symbol, String clientOrderId, Throwable t) {
        Throwable cause = (t instanceof ExecutionException && t.getCause() != null) ? t.getCause() : t;
        LOG.warnf("[exec] %s failed for %s clientOrderId=%s: %s", stage, symbol, clientOrderId, cause.toString());
    }
}
